Add BinanceTestNet Configuration
smartcontractkit/box pull request #30
Opened 2020-12-27 02:30 UTC by aadorian

Add Binance TestNet Configuration and dotenv
<img width="1060" alt="Screen Shot 2020-12-26 at 11 17 59 PM" src="https://user-images.githubusercontent.com/734790/103162670-36060300-47d2-11eb-8890-e3cf74cc388e.png">
<img width="1140" alt="Screen Shot 2020-12-26 at 11 14 40 PM" src="https://user-images.githubusercontent.com/734790/103162673-39998a00-47d2-11eb-8a6d-6768f9a2c4e4.png">

2021-01-11 12:45 UTC, thodges-gh requested changes

2021-01-11 12:45 UTC, thodges-gh commented on scripts/fund-contract.js
> +    const tokenAddress = '0x761429d8887600dacE56BfA13651C018C1F0C538' //address of the deploy MyContract
Having to change a deployment script's source is not user friendly. Can we make these environment variables instead that also take into consideration the deployed contract?

2021-01-11 12:45 UTC, thodges-gh commented on scripts/fund-contract.js
> +//const payment = process.env.TRUFFLE_CL_BOX_PAYMENT || '1000000000000000000'
Please don't comment out code.

2021-02-04 01:43 UTC, se3000 commented
@aadorian it looks like you resolved the comments but didn't push the fixes. Mind pushing those?

2021-02-04 04:37 UTC, aadorian commented
> @aadorian it looks like you resolved the comments but didn't push the fixes. Mind pushing those?

Shure I will close this and pr ...

2021-02-04 04:37 UTC, closed without merging